on:
  push:
    tags:
      - "*"

name: release

jobs:
  compare:
    name: compare
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: "npm install -g deno"
      - run: "deno bundle ./src/mod.ts --output local"
      - run: "deno bundle jsr:@hazae41/tscousin@${{github.ref_name}} --output remote"
      - run: "diff local remote"
      - run: "[[ -z $(diff local remote) ]]"
